#!/bin/bash

solvers=("Euler" "NS" "QG" "QGf" "QGf_hyper" "NS_rot")

for str in ${solvers[@]}; do
  cd solvers/$str
  echo "COMPILING SOLVER: $str"
  make -f makefile_gnu $1
  echo "DONE"
  echo ""
  cd ../../
done
